version: '3'
services:

  database:
      image: postgres:11
      volumes:
          - ./db_data/pgdata:/var/lib/postgresql/data/
      environment:
          POSTGRES_USER: django
          POSTGRES_HOST_AUTH_METHOD: trust
      ports:
        - "5432:5432"

  api:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
          - ./project/:/django
      ports:
          - "8900:8000"
      env_file: &envfile
        - env.env
      depends_on:
        - database
