apiVersion: apps/v1
kind: Deployment
metadata:
  name: locate-api
  labels:
    app: locate-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locate-api
  template:
    metadata:
      labels:
        app: locate-api
    spec:
      containers:
        - name: locate-api
          image: urandu/loccate:latest2
          args: ["python", "project/manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: locate-postgres-credentials
                  key: user

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: locate-postgres-credentials
                  key: password

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: locate-postgres-credentials
                  key: db_name

            - name: DATABASE_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: locate-postgres-credentials
                  key: db_host
