apiVersion: v1
kind: Secret
metadata:
  name: locate-postgres-credentials
type: Opaque
data:
  user: ZGphbmdv
  password: d2Vha19wYXNzd29yZA==
  db_name: ZGphbmdv
  db_host: bG9jY2F0ZS1wb3N0Z3Jlcy1zZXJ2aWNl