kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: locate-postgres-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: locate-postgres-pv